#!/bin/bash

# a shell wrapper for running commands from make. Adds colors, command echoing and timing

set -o pipefail

NO_COLOR=`echo -e "\033[0m"`
RED=`echo -e "\033[31m"`
YELLOW=`echo -e "\033[33m"`
MAGENTA=`echo -e "\033[35m"`
CYAN=`echo -e "\033[36m"`
WHITE=`echo -e "\033[37m"`


if [ -t 1 ] ; then
    # invoked as part of make recipe
    
    # time measurement (only in seconds because Macs don't have gnu time)
    start=`date +%s`

    # prints the make target and recipe command, with colors
    echo $WHITE$1:$CYAN ${@:3}$NO_COLOR

    # runs the command 
    /bin/bash -o pipefail -c "${@:3}" 2> >(
        # makes stderr output red
        while IFS= read line; do
            echo "$MAGENTA$1: $RED$line$NO_COLOR" >&2;
        done
    ) | (
        while IFS= read line; do
            echo "$YELLOW$1: $NO_COLOR$line";
        done
    )

    # keep return code
    return_code=$?

    # prints the elapsed time
    echo $CYAN$1:$YELLOW $(($(date +%s) - $start)) seconds$NO_COLOR

    exit $return_code
else
    # invoked from make via $(shell command)
    /bin/bash -o pipefail -c "${@:3}"
fi


